export * from "./TsClass.model";
export * from "./TsComment.model";
export * from "./TsFile.model";
export * from "./TsFunction.model";
export * from "./TsParam.model";
export * from "./TsProperty.model";
export * from "./TsInterface.model";
export * from "./TsExport.model";
export * from "./KeyWord.type";
