name: Node.js CI - Testing Flow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Testing functions and modules
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
